"use client";
import {useEffect,useMemo,useState} from "react";
import {Activity,BarChart3,Bell,CalendarDays,Check,CheckCircle2,ChevronDown,ChevronRight,Clock3,FileText,LayoutDashboard,ListFilter,Menu,MessageCircle,MoreHorizontal,Paperclip,Plus,Search,Settings,Sparkles,Target,Users,X} from "lucide-react";
type Status="Backlog"|"In progress"|"Review"|"Done";
type Task={id:number;title:string;tag:string;status:Status;priority:"High"|"Medium"|"Low";date:string;comments:number;files:number;owner:string};
const seed:Task[]=[
{id:1,title:"Finalize enterprise SSO flow",tag:"Authentication",status:"Backlog",priority:"High",date:"Sep 19",comments:4,files:2,owner:"AM"},
{id:2,title:"Map onboarding empty states",tag:"UX",status:"Backlog",priority:"Medium",date:"Sep 21",comments:2,files:0,owner:"NK"},
{id:3,title:"Build workspace activity feed",tag:"Platform",status:"In progress",priority:"High",date:"Today",comments:8,files:3,owner:"JD"},
{id:4,title:"Upgrade file preview service",tag:"Infrastructure",status:"In progress",priority:"Medium",date:"Sep 20",comments:3,files:5,owner:"SL"},
{id:5,title:"QA permission inheritance",tag:"Security",status:"Review",priority:"High",date:"Today",comments:6,files:1,owner:"AM"},
{id:6,title:"Polish workload visualization",tag:"Analytics",status:"Review",priority:"Low",date:"Sep 23",comments:2,files:2,owner:"NK"},
{id:7,title:"Migrate audit events",tag:"Backend",status:"Done",priority:"Medium",date:"Sep 16",comments:5,files:1,owner:"JD"},
{id:8,title:"Ship saved project views",tag:"Product",status:"Done",priority:"High",date:"Sep 15",comments:9,files:4,owner:"SL"}];
const tones:Record<string,string>={AM:"violet",NK:"gold",JD:"blue",SL:"green",YO:"blue",MS:"violet"};
function Avatar({id}:{id:string}){return <i className={"avatar "+tones[id]}>{id}</i>}
function Head({title,sub}:{title:string;sub:string}){return <div className="head"><div><h2>{title}</h2><p>{sub}</p></div><button><MoreHorizontal/></button></div>}
export default function Home(){
 const[view,setView]=useState<"Overview"|"Board"|"Analytics">("Overview"),[tasks,setTasks]=useState(seed),[query,setQuery]=useState(""),[show,setShow]=useState(false),[title,setTitle]=useState(""),[menu,setMenu]=useState(false),[toast,setToast]=useState("");
 const filtered=useMemo(()=>tasks.filter(t=>t.title.toLowerCase().includes(query.toLowerCase())),[tasks,query]);
 useEffect(()=>{const d=document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}};if(!d.modelContext?.registerTool)return;const c=new AbortController();void Promise.resolve(d.modelContext.registerTool({name:"start_task_creation",title:"Start task creation",description:"Open the TeamFlow task creation dialog and optionally prefill its title.",inputSchema:{type:"object",properties:{title:{type:"string"}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const value=typeof input==="object"&&input&&"title" in input?String((input as {title?:unknown}).title??""):"";setTitle(value);setShow(true);return{status:"ready",title:value}}},{signal:c.signal})).catch(()=>{});return()=>c.abort()},[]);
 function add(){if(!title.trim())return;setTasks([{id:Date.now(),title:title.trim(),tag:"Product",status:"Backlog",priority:"Medium",date:"Sep 25",comments:0,files:0,owner:"YO"},...tasks]);setTitle("");setShow(false);setToast("Task added to Website redesign");setTimeout(()=>setToast(""),2400)}
 return <main><aside className={menu?"side open":"side"}>
  <div className="brand"><b><Check/></b>teamflow<button onClick={()=>setMenu(false)}><X/></button></div>
  <div className="workspace"><Avatar id="AM"/><span><strong>Acme Studio</strong><small>Business workspace</small></span><ChevronDown/></div>
  <p className="label">Workspace</p>{[[LayoutDashboard,"Overview"],[CheckCircle2,"My work"],[Bell,"Inbox"],[BarChart3,"Reports"]].map(([I,n],i)=><button className={"nav "+(i===0?"active":"")} key={String(n)}><I/><span>{String(n)}</span>{n==="Inbox"&&<em>3</em>}</button>)}
  <p className="label">Projects <Plus/></p>{[["Website redesign","#7667ef"],["Mobile experience","#f0a82e"],["Growth campaigns","#16a6c8"]].map(([n,c])=><button className="nav project" key={n}><i style={{background:c}}/><span>{n}</span><ChevronRight/></button>)}
  <div className="sidefoot"><button className="nav"><Users/><span>Invite teammates</span></button><button className="nav"><Settings/><span>Settings</span></button><div className="profile"><Avatar id="MS"/><span><strong>Maya Singh</strong><small>Product lead</small></span><MoreHorizontal/></div></div>
 </aside><section className="app"><header className="top"><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks, projects, people…"/><kbd>⌘ K</kbd></div><div className="actions"><button className="bell"><Bell/><i/></button><div className="stack"><Avatar id="AM"/><Avatar id="NK"/><Avatar id="JD"/><span>+8</span></div><button className="primary" onClick={()=>setShow(true)}><Plus/>New task</button></div></header>
 <div className="content"><div className="intro"><div><small><b>W</b> Website redesign / Overview</small><h1>Good morning, Maya <span>✦</span></h1><p>Here’s what’s moving across your project today.</p></div><div><button><Users/>Share</button><button><MoreHorizontal/></button></div></div><div className="tabs">{(["Overview","Board","Analytics"] as const).map(v=><button className={view===v?"on":""} onClick={()=>setView(v)} key={v}>{v}</button>)}</div>
 {view==="Overview"?<Overview tasks={tasks} board={()=>setView("Board")}/>:view==="Board"?<Board tasks={filtered} query={query}/>:<Analytics/>}</div></section>
 {show&&<div className="shade" onMouseDown={()=>setShow(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalhead"><span><Plus/></span><div><h2>Create a new task</h2><p>Add it to the Website redesign backlog.</p></div><button onClick={()=>setShow(false)}><X/></button></div><label>Task name<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="What needs to be done?"/></label><div className="options"><button><Target/>Medium priority<ChevronDown/></button><button><CalendarDays/>Sep 25<ChevronDown/></button></div><footer><button onClick={()=>setShow(false)}>Cancel</button><button className="primary" onClick={add}>Create task</button></footer></div></div>}{toast&&<div className="toast"><b><Check/></b>{toast}</div>}</main>}
function Overview({tasks,board}:{tasks:Task[];board:()=>void}){return <div className="overview"><section className="metrics"><Metric I={CheckCircle2} tone="purple" value={String(tasks.length*4)} label="Tasks completed" chip="+12%"/><Metric I={Clock3} tone="amber" value="18" label="Hours saved" chip="This week"/><Metric I={Activity} tone="cyan" value="94%" label="On-time delivery" chip="+8%"/><Metric I={Target} tone="green" value="Project health" label="7 of 9 milestones reached" chip="On track"/></section>
 <section className="card velocity"><Head title="Project velocity" sub="Completed work across the last 8 weeks"/><div className="chartstat"><div><strong>126</strong><span>tasks completed</span></div><em><Sparkles/>14.2% vs prior period</em></div><svg viewBox="0 0 680 150"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#6557e8" stopOpacity=".25"/><stop offset="1" stopColor="#6557e8" stopOpacity="0"/></linearGradient></defs>{[30,70,110,148].map(y=><line key={y} x1="0" y1={y} x2="680" y2={y} stroke="#e9e7ef" strokeDasharray="4 7"/>)}<path d="M0 135C70 128 80 109 142 115s76-26 132-16 75-41 130-27 82-35 131-20 85-38 145-29v127H0Z" fill="url(#g)"/><path d="M0 135C70 128 80 109 142 115s76-26 132-16 75-41 130-27 82-35 131-20 85-38 145-29" fill="none" stroke="#6557e8" strokeWidth="4" strokeLinecap="round"/></svg><div className="axis"><span>Jul 29</span><span>Aug 12</span><span>Aug 26</span><span>Sep 9</span><span>Sep 16</span></div></section>
 <section className="card activity"><Head title="Recent activity" sub="Updates from your team"/>{[["AM","Alex moved SSO flow to Review","8m"],["NK","Nora commented on Empty states","24m"],["JD","Jon uploaded audit-events.csv","1h"],["SL","Sam completed Saved views","3h"]].map(([a,t,d])=><div className="event" key={t}><Avatar id={a}/><p>{t}<small>{d} ago</small></p></div>)}<button className="link">View all activity <ChevronRight/></button></section>
 <section className="card prioritywork"><Head title="Priority work" sub="Tasks needing your attention"/>{tasks.filter(t=>t.priority==="High").slice(0,4).map(t=><div className="row" key={t.id}><button className="check"/><p><strong>{t.title}</strong><small>{t.tag}</small></p><b className="high">High</b><Avatar id={t.owner}/><span>{t.date}</span><MoreHorizontal/></div>)}<button className="link" onClick={board}>Open task board <ChevronRight/></button></section>
 <section className="card sprint"><Head title="Sprint progress" sub="Sep 9 – Sep 22"/><div className="big"><strong>25 <small>/ 32 tasks</small></strong><b>78%</b></div><div className="progress"><i/></div>{[["Completed","23","done"],["In progress","6","doing"],["Backlog","3","backlog"]].map(([n,v,c])=><div className="status" key={n}><i className={c}/><span>{n}</span><b>{v}</b></div>)}</section></div>}
function Metric({I,tone,value,label,chip}:{I:typeof Activity;tone:string;value:string;label:string;chip:string}){return <article className="metric"><div><b className={tone}><I/></b><em>{chip}</em></div><strong>{value}</strong><p>{label}</p><div className={"visual "+tone}>{[1,2,3,4,5,6,7].map(i=><i key={i}/>)}</div></article>}
function Board({tasks,query}:{tasks:Task[];query:string}){let cols:Status[]=["Backlog","In progress","Review","Done"];return <><div className="boardbar"><span><button><ListFilter/>Filter</button>{tasks.length} tasks {query&&"matching search"}</span><div className="stack"><Avatar id="AM"/><Avatar id="NK"/><Avatar id="JD"/></div></div><div className="board">{cols.map((c,i)=><section key={c}><header><span><i className={"s"+i}/><b>{c}</b><em>{tasks.filter(t=>t.status===c).length}</em></span><Plus/></header>{tasks.filter(t=>t.status===c).map(t=><article key={t.id}><div><small>{t.tag}</small><MoreHorizontal/></div><h3>{t.title}</h3><p><b className={t.priority.toLowerCase()}>{t.priority}</b><span><CalendarDays/>{t.date}</span></p><footer><Avatar id={t.owner}/><span><i><MessageCircle/>{t.comments}</i><i><Paperclip/>{t.files}</i></span></footer></article>)}</section>)}</div></>}
function Analytics(){return <div className="analytics"><section className="card bars"><Head title="Delivery performance" sub="Planned vs completed tasks by month"/><div className="barchart">{[[55,45],[64,58],[72,61],[68,72],[84,76],[92,88]].map(([a,b],i)=><div key={i}><span><i style={{height:a+"%"}}/><i style={{height:b+"%"}}/></span><small>{["Apr","May","Jun","Jul","Aug","Sep"][i]}</small></div>)}</div></section><section className="card workload"><Head title="Team workload" sub="Open tasks by owner"/>{[["AM","Alex",82],["NK","Nora",64],["JD","Jon",71],["SL","Sam",48]].map(([a,n,v])=><div className="load" key={String(n)}><Avatar id={String(a)}/><span><b>{n}<em>{v}%</em></b><i><strong style={{width:v+"%"}}/></i></span></div>)}</section>{[[FileText,"1,284","Files shared securely","+18% this quarter"],[Users,"26","Active collaborators","Across 4 teams"],[CheckCircle2,"4.8 days","Average cycle time","↓ 1.2 days"]].map(([I,v,l,n])=><section className="card stat" key={String(l)}><b><I/></b><strong>{String(v)}</strong><p>{String(l)}</p><em>{String(n)}</em></section>)}</div>}
